### ISSUE TITLE
Update shebangs

### ISSUE THREAD

**Issue by mhalano** [mrschyte/taskwarrior-hooks#2]
Your hooks work great, they just need one change: modify the shebang from "/bin/sh" to "/bin/bash". They use "[[" but this option is internal to bash and it's not present in sh.

**Comment by mrschyte** [comment]
Thanks for reporting this. I've decided to make the scripts POSIX compatible instead of changing the shebang to bash. I've verified with dash and the hooks executed fine.

Please try with the latest commit and let me know if you get any error 9fb2e53462a97180d98f09056a5dea5ef22ccfc9

**Comment by mhalano** [comment]
@mrschyte Seems fine to me now. I will close this issue since it is more related to incompatibility with '[[' than any other thing.
